# Generated by Django 5.0.7 on 2024-08-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
