# Generated by Django 5.0.7 on 2024-09-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
